//! Generated protobuf types for the Atlas event wire contract.
//!
//! Nothing in this crate is hand-written logic. The `.proto` files under
//! `proto/atlas/events/v1/` are the source of truth; see
//! `docs/specs/2026-09-24-event-schema-design.md`.

/// `atlas.events.v1` — generated by prost.
#[allow(clippy::all)]
pub mod v1 {
    include!(concat!(env!("OUT_DIR"), "/atlas.events.v1.rs"));
}

/// Encoded `FileDescriptorSet` for `atlas.events.v1` (used for protobuf-JSON in tests and tools).
pub const FILE_DESCRIPTOR_SET: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/atlas_events_v1.fds.bin"));
